### PR TITLE
Add brew

### LINKED ISSUE #25: Add brew installation
**Is your feature request related to a problem? Please describe.**
I want to install `mermaid-cli` on my MacOS.

**Describe the solution you'd like**
Please add brew formula, that help mac-users to easy install `mermaid-cli`.

### PR DESCRIPTION
**Pull request by BastianZim**
## :bookmark_tabs: Summary

Brief description about the content of your PR.

Resolves #25

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

## :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid-cli/blob/master/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `master` branch

New implementation of #81 due to conflicts.

### CODE REVIEW

**Comment by BastianZim** [comment]
cc @MindaugasLaganeckas

**Comment by BastianZim** [comment]
@knsv Would you mind having a look at this PR? It's just a small addition to the docs but @MindaugasLaganeckas seems to be absent currently.

**Review by GDFaber — APPROVED** [review]

**Comment by GDFaber** [comment]
LGTM, thank you for your contribution.

**Comment by BastianZim** [comment]
Thanks @GDFaber!

**Pull request merged**
