### PR TITLE
Added process.title

### PR DESCRIPTION
**Pull request by Yash-Singh1**
Added in `process.title`

### CODE REVIEW

**Comment by MindaugasLaganeckas** [comment]
@Yash-Singh1 thank you for your PR! What problem does your PR solve?

**Comment by Yash-Singh1** [comment]
This PR doesn't solve any problem. It just adds in a feature.

**Comment by MindaugasLaganeckas** [comment]
What is the purpose of the feature? When would it beneficial for others to use this feature?

**Comment by Yash-Singh1** [comment]
Here is a documentation for `process.title`:
[https://nodejs.org/api/process.html#process_process_title](https://nodejs.org/api/process.html#process_process_title)
All that this PR does is, allows people to use the `ps` command or the `System Monitor`, `Task Manager`, etc. to identify the process for the `mermaid-cli`.

**Review by MindaugasLaganeckas — APPROVED** [review]

**Pull request merged**
