### PR TITLE
Add brew

### LINKED ISSUE #25: Add brew installation
**Is your feature request related to a problem? Please describe.**
I want to install `mermaid-cli` on my MacOS.

**Describe the solution you'd like**
Please add brew formula, that help mac-users to easy install `mermaid-cli`.

### PR DESCRIPTION
**Pull request by BastianZim**
## :bookmark_tabs: Summary
Brief description about the content of your PR.
_Adds brew as a download option_
Resolves #25 
## :straight_ruler: Design Decisions
Describe the way your implementation works or what design decisions you made if applicable.
_N.A._
### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [ ] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `master` branch 

The PR (~~https://github.com/Homebrew/homebrew-core/pull/65521~~ new PR: https://github.com/Homebrew/homebrew-core/pull/67804) at brew is not yet merged, as there are some problems with Chromium but I just wanted to create this draft request for awareness and in case there are any ideas here about fixing Chromium. Right now, there is a temporary solution but maybe there is something more permanent that we're overlooking.

### CODE REVIEW

**Comment by MindaugasLaganeckas** [comment]
@BastianZim : please, mark your PR as draft and let me know, when it can be merged to master.
Thanks a lot for your contribution! :smile:

**Comment by BastianZim** [comment]
@MindaugasLaganeckas It should already be marked as a draft. Would you mind double-checking in case I marked it incorrectly?
Pleasure! Sorry that it's taking so long but there seems to be an issue with the tests that brew doesn't like and I'm not sure how to fix it, unfortunately.

**Comment by MindaugasLaganeckas** [comment]
@BastianZim : thank you very much for the update! Just ping me, when the other end is ready! Merry Christmas! 🎄

**Comment by BastianZim** [comment]
@MindaugasLaganeckas 
Of course, will do! Merry Christmas to you too!

**Comment by BastianZim** [comment]
@MindaugasLaganeckas Sort of a late Christmas present from the Homebrew maintainers 😄 but the PR has now been merged https://github.com/Homebrew/homebrew-core/pull/67804#issuecomment-752765968 and mermaid-cli is available on brew.
Before I mark this ready for review just two comments:
1) The `README.md` switches between ## and ### for the headlines and I couldn’t find the logic behind it. Should the brew install section be two or three #? 
2) I subscribed to new mermaid-cli releases, as the brew version needs to be manually updated each time, so that I don’t miss them but in case I do or if there are any issues regarding brew, feel free to ping me or just assign the issue to me (Not sure if that’s possible though...).

**Comment by BastianZim** [comment]
@MindaugasLaganeckas Happy new year! Just wanted to quickly check if you already had some time to review my questions, as I could then add a fix, if required.

**Comment by BastianZim** [comment]
Just saw that there are conflicts prohibiting rebase, seems to be because of the reformatting in #88. Should I just open a new PR?

**Comment by BastianZim** [comment]
@MindaugasLaganeckas Just wanted to check if there is anything I should change?

**Comment by BastianZim** [comment]
@MindaugasLaganeckas Are you still there?

**Pull request closed without merging**
