### PR TITLE
Allow output paths to contain dots

### LINKED ISSUE #258: Output path can't has period '.' symbol, or will encounter ENOENT: no such file or directory
**Describe the bug**
Output path can't has period '.' symbol, or will encounter ENOENT: no such file or directory

**To Reproduce**

1. npx mmdc -i test.md -o /path/to/has.period/test.png
2. [Error: ENOENT: no such file or directory, open '/path/to/has-1.period/test.png']

**Expected behavior**
Resolve period properly

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Ubuntu 20.04
- Browser 
- Version 8.14.0

**Additional context**

### PR DESCRIPTION
**Pull request by ShaneMurphy2**
Fixes #258

### CODE REVIEW

**Review by MindaugasLaganeckas — APPROVED** [review]
Thank you for the pr! 🙂

**Comment by ShaneMurphy2** [comment]
> Thank you for the pr! 🙂

😄

**Comment by yasincad** [comment]
Thank you for the fix, I was just looking for it. 

When can we expect a new version including this fix?

**Comment by MindaugasLaganeckas** [comment]
We will release CLI, when a new version of mermaid is released. Unfortunately, I do not have an ETA.

**Pull request merged**
