### PR TITLE
Add optional CR to markdown graph detection regex.

### LINKED ISSUE #183: Markdown Graph Detection Broken for CRLF Files
Detection of mermaid graphs embedded in markdown does not work for CRLF (\r\n) files.

Saving the file as LF only works as a temporary workaround.

It looks like line 206 in  src/index.js is the culprit.

Proposed solutions
 * Strip all \r from the string `str.replace('\r', '')`
 * Modify regex to catch optional carriage return `const matches = definition.match(/^```(?:mermaid)(\r?\n([\s\S]*?))```$/gm);`

### PR DESCRIPTION
**Pull request by dominicdoty**
## :bookmark_tabs: Summary
Add optional CR to markdown graph detection regex.
Add test CRLF markdown file.
Add .gitattributes to prevent git from converting CRLF to LF in test file.

Resolves #183

### CODE REVIEW

**Comment by Yash-Singh1** [comment]
Should we update the regular expression here too?

https://github.com/dominicdoty/mermaid-cli/blob/fix/crlf-markdown-graph-detection/src/index.js#L210

Just to keep the regular expressions in sync, I think there should be a constant that contains it. About the fact that the first reference has the flags `gm`, you can create the regular expression without any flags and do the following:

```js
new RegExp(myRegExpConstant, 'gm')
```

**Comment by MindaugasLaganeckas** [comment]
@dominicdoty : very nice work! I can see that when running tests, we do not handle a case for `md` files. Can you add a similar line to this one https://github.com/dominicdoty/mermaid-cli/blob/f3851d7e8cd08a821d48a407604f5e6f6f11213b/run-tests.sh#L8 to also export `png` from `md`?
Also have a look at @Yash-Singh1 comment.
Thanks for a very good PR! 😉

**Comment by MindaugasLaganeckas** [comment]
I will accept your PR even though it is not completely finished just to give you the credit and encourage to contribute to open source in the future. I will address the comments myself.

Thanks for the help! 😄

**Comment by nicojs** [comment]
I just spent 1 hour trying to figure out what was wrong. CRLF coming back to bite me once again. Great to see it is already fixed! A release would be _much_ appreciated!

**Pull request merged**
