### PR TITLE
Change Docker workdir

### PR DESCRIPTION
**Pull request by daamien**
Following our discussion on issue #435

### CODE REVIEW

**Review by aloisklink — APPROVED** [review]
Looks good to me!

@MindaugasLaganeckas, do you know if @daamien has to `git rebase` their commits?

Currently, this PR has commit https://github.com/mermaid-js/mermaid-cli/pull/470/commits/265e2e0f23a52848313fc72f7f1667ea8d3196a4, which was identical to https://github.com/mermaid-js/mermaid-cli/commit/430a537e6f849922c55bc3f9a94d4314b1a49672 before that got merged via rebase in https://github.com/mermaid-js/mermaid-cli/pull/469, but now that they have different commit hashes, I've got no idea if GitHub will detect that and auto-delete the newer commit.

**Comment by daamien** [comment]
Sorry I moved too quickly on this one, I think I did a merge instead of git rebase... 

I can create a new PR and cherry pick the commit [f01d8d7](https://github.com/mermaid-js/mermaid-cli/pull/470/commits/f01d8d7b3b07f0f644a6b23b9700ee5520414a78)

**Comment by daamien** [comment]
Closed and Replaced by https://github.com/mermaid-js/mermaid-cli/pull/472

**Comment by MindaugasLaganeckas** [comment]
Hey @aloisklink! I would have done exactly the same what @daamien has done 😄

**Pull request closed without merging**
